PizzaApp/Controllers/PizzaController.cs
using Microsoft.AspNetCore.Mvc;
using PizzaApp.Models;
using PizzaApp.ViewModels;

namespace PizzaApp.Controllers
{
    public class PizzaController : Controller
    {
        private readonly IPizzaRepository _pizzaRepository;
        private readonly ICategoryRepository _categoryRepository;

        public PizzaController(IPizzaRepository pizzaRepository, ICategoryRepository categoryRepository)
        {
            _pizzaRepository = pizzaRepository;
            _categoryRepository = categoryRepository;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult List()
        {
            // Instantiate the Pizza View Model
            PizzaListViewModel pizzaListViewModel = new PizzaListViewModel();
            // Fill in the pizza's data point of the view model from the repository
            pizzaListViewModel.Pizzas = _pizzaRepository.AllPizzas;
            // Fill in the category data popint of the view model from the repository
            pizzaListViewModel.CurrentCategory = "Meat Pizza";

            // return the view
            return View(pizzaListViewModel);
        }
        public IActionResult Details(int id)
        {
            // gets the pizza by its id from the repository and assigns to a variable to use
            var pizza = _pizzaRepository.GetPizzaById(id);

            if (pizza == null)
            {
                return NotFound();
            }
            // return the view
            return View(pizza);
        }
    }
}

PizzaApp/Views/Shared/_Carousel.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<div class="row carousel-holder">
    <div class="col-md-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>

            </ol>

            <div class="carousel-inner">
                <div class="item active">
                    <img class="slide-image" src="~/images/pepperoni.png" alt="" />
                </div>
                <div class="item">
                    <img class="slide-image" src="~/images/theworks.jpg" alt="" />
                </div>
                <div class="item">
                    <img class="slide-image" src="~/images/veggies.jpg" alt="" />
                </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
</div>

PizzaApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PizzaApp</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/PizzaApp.styles.css" asp-append-version="true" />

    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <script src="~/lib/jquery/jquery.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PizzaApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pizza" asp-action="List">All Pizzas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - PizzaApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PizzaApp/Views/Shared/_PizzaCard.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Pizza

<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img src="@Model.ImageThumbnailUrl" alt="" />
        <div class="caption">
            <h3 class="pull-right">@Model.Price.ToString("c")</h3>
            <h3>
                <a asp-controller="Pizza" asp-action="Details" asp-route-id="@Model.PizzaId">@Model.Name</a>
            </h3>
            <p>@Model.ShortDescription</p>
        </div>
    </div>
</div>